sinfor:
  netty:
    port: 9898

spring:
  redis:
    database: 10
    host: localhost
    port: 6379
    password: 123456

  datasource:
    url: jdbc:oracle:thin:@14.29.115.237:1799/xfdb
    username: xfnew
    password: xfnew
    driver-class-name: oracle.jdbc.OracleDriver

# 数据库中很多直接使用的驼峰命名，关闭驼峰转下划线自动转换
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

# 缓存默认时间
cache:
  default:
    expire-time: 200
  # 不同的缓存空间使用不同的配置
  user:
    expire-time: 100
    name: user